//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebClient.EmployeeService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmployeeService.EmployeeWSSoap")]
    public interface EmployeeWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmpployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllEmpployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllEmpployees", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllEmpployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpployeesByJobID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetEmpployeesByJobID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmpployeesByJobID", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetEmpployeesByJobIDAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJobs", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetJobs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetJobs", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetJobsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmployeeWSSoapChannel : WebClient.EmployeeService.EmployeeWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmployeeWSSoapClient : System.ServiceModel.ClientBase<WebClient.EmployeeService.EmployeeWSSoap>, WebClient.EmployeeService.EmployeeWSSoap {
        
        public EmployeeWSSoapClient() {
        }
        
        public EmployeeWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmployeeWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmployeeWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetAllEmpployees() {
            return base.Channel.GetAllEmpployees();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllEmpployeesAsync() {
            return base.Channel.GetAllEmpployeesAsync();
        }
        
        public System.Data.DataSet GetEmpployeesByJobID(int id) {
            return base.Channel.GetEmpployeesByJobID(id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetEmpployeesByJobIDAsync(int id) {
            return base.Channel.GetEmpployeesByJobIDAsync(id);
        }
        
        public System.Data.DataSet GetJobs() {
            return base.Channel.GetJobs();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetJobsAsync() {
            return base.Channel.GetJobsAsync();
        }
    }
}
